FROM alpine:3.21
LABEL org.opencontainers.image.authors="andreas@staffbase.com"

RUN apk add --no-cache \
    curl \
    build-base \
    go \
    imagemagick-dev \
    vips-dev \
    vips-cpp \
    vips-magick \
    vips-poppler \
    vips-heif \
    vips-jxl

ARG GOLANGCILINT_VERSION=1.63.4
RUN curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/bin v${GOLANGCILINT_VERSION}
